// This is a generated file; do not edit or check into version control.
// It will be regenerated by `flutter build ios`.
// The Flutter framework is built as a dynamic framework to allow linking to
// any architecture.
FLUTTER_FRAMEWORK_DIR=/usr/local/flutter/bin/cache/artifacts/engine/ios
FLUTTER_BUILD_MODE=debug
