name: tennisdeagle
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 自动安装CocoaPods依赖
        run: |
          if [ -f Podfile ]; then
            pod install
          fi

      - name: 免签名编译IPA
        run: |
          # 替换成你的项目名称
          PROJECT_NAME="你的项目名称"
          # 替换成你的项目Bundle ID
          BUNDLE_ID="com.xxx.testapp"
          # 用了CocoaPods的话，把下面的-project改成-workspace，后缀改成.xcworkspace
          xcodebuild -project ${PROJECT_NAME}.xcodeproj \
                     -scheme ${PROJECT_NAME} \
                     -configuration Debug \
                     -sdk iphoneos \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     clean build

          # 打包生成IPA
          mkdir -p Payload
          cp -r build/Debug-iphoneos/${PROJECT_NAME}.app Payload/
          zip -r ${PROJECT_NAME}.ipa Payload/

      - name: 输出IPA文件
        uses: actions/upload-artifact@v4
        with:
          name: 编译完成的IPA安装包
          path: *.ipa
